### ISSUE TITLE
TOML Trouble

### ISSUE THREAD

**Issue by arkaprava-jana** [xfhg/intercept#135]
Getting Compliant Output with Warning while ideally it should be non-compliant.

File to scan: https://github.com/grafana/grafana/blob/main/conf/ldap.toml

Rule:

 ```
- name: TOML ASSURE - Minimum TLS Version 1.2
    id: 1001
    description: Assure Minimum TLS Version
    error: Misconfiguration or omission is fatal
    tags: TLS
    type: toml
    fatal: false
    enforcement: true
    environment: all
    confidence: high
    toml_filepattern: "ldap.toml"
    toml_structure: |
      servers: [{minimum_tls_version:"1.2"}]
      ...
```

Output:

│
├ TOML Rule # 1001
│ Rule name :  TOML ASSURE - Minimum TLS Version 1.2
│ Rule description :  Assure Minimum TLS Version
│ Impacted Env :  all
│ Confidence :  high
│ Tags :  TLS
│ File pattern :  ldap.toml
│ TOML pattern :  servers: [{minimum_tls_version:"1.2"}]
...

│
│ Scanning..
│ File : tests/ldap.toml
│ Hash : 1fd89962937a50cdabc3560e3e7642866f7ef450fafa8b4e18c43da895390b85
│
│ Warning : TOML File not valid
├ Missing keys feature not available
│
│
│ Compliant
│

**Comment by xfhg** [comment]
Correct on the compliance mishap, but the policy has a typo : 

toml_structure: |
     servers: [{**minimum_tls_version**:"1.2"}]
     ...

ldap.toml:

**min_tls_version** = ""

**Comment by xfhg** [comment]
├ Missing keys feature not available

This is a missing feature

**Comment by arkaprava-jana** [comment]
What should be the correct policy? I converted the toml to json and servers is a list so tried to follow the syntax.

Here the value is missing not the key, I guess it is a toml parsing error. Is not it?

**Comment by arkaprava-jana** [comment]
Correction of policy file solved the issue.
