### ISSUE TITLE
the recent releases are gone

### ISSUE THREAD

**Issue by chenrui333** [xfhg/intercept#155]
👋 not sure what is going on, but all the recent release tags like 1.5.2, 1.5.5, 1.5.9, 1.6.1 are all gone

- https://github.com/Homebrew/homebrew-core/pull/141271
- https://github.com/Homebrew/homebrew-core/pull/155424
- https://github.com/Homebrew/homebrew-core/pull/156363
- https://github.com/Homebrew/homebrew-core/pull/160714

**Comment by chenrui333** [comment]
considering you had 1.6.1 release before, maybe create a release after it? thanks.

cc @xfhg

**Comment by xfhg** [comment]
Hello @chenrui333, we were not aware of the presence of intercept in homebrew. Unfortunately versions 1.X were mistakenly tagged and had to be rolled back. this new v1 is not backwards compatible with them, bringing a faster intercept core and richer policy definitions along with new features. If it help I can put up a repo with all the old code and tags as intercept-legacy. Or we can discuss other solutions.
