### ISSUE TITLE
Linux bootstrap script Scan - Query Not an Issue

### ISSUE THREAD

**Issue by Kannancsq** [xfhg/intercept#44]
Dear Team

Would like to know does the Intecept application scan through bootstrap scripts based on the Patterns.

Thanks
Kannan V

**Comment by xfhg** [comment]
@Kannancsq, **intercept** is an abstraction on top of ripgrep which can :

- Like other tools specialized to code search, ripgrep defaults to recursive directory search and won't search files ignored by your .gitignore/.ignore/.rgignore files. It also ignores hidden and binary files by default. ripgrep also implements full support for .gitignore, whereas there are many bugs related to that functionality in other code search tools claiming to provide the same functionality.
- ripgrep can search specific types of files. For example, rg -tpy foo limits your search to Python files and rg -Tjs foo excludes JavaScript files from your search. ripgrep can be taught about new file types with custom matching rules.
- ripgrep supports many features found in grep, such as showing the context of search results, searching multiple patterns, highlighting matches with color and full Unicode support. Unlike GNU grep, ripgrep stays fast while supporting Unicode (which is always on).
- ripgrep has optional support for switching its regex engine to use PCRE2. Among other things, this makes it possible to use look-around and backreferences in your patterns, which are not supported in ripgrep's default regex engine. PCRE2 support can be enabled with -P/--pcre2 (use PCRE2 always) or --auto-hybrid-regex (use PCRE2 only if needed). An alternative syntax is provided via the --engine (default|pcre2|auto-hybrid) option.
- ripgrep supports searching files in text encodings other than UTF-8, such as UTF-16, latin-1, GBK, EUC-JP, Shift_JIS and more. (Some support for automatically detecting UTF-16 is provided. Other text encodings must be specifically specified with the -E/--encoding flag.)
- ripgrep supports searching files compressed in a common format (brotli, bzip2, gzip, lz4, lzma, xz, or zstandard) with the -z/--search-zip flag.
- ripgrep supports arbitrary input preprocessing filters which could be PDF text extraction, less supported decompression, decrypting, automatic encoding detection and so on.

Out of the box with default configuration it can target any text / compressed text against your defined regular expressions which for **intercept** we call **policies**. So yes it can and it was its main purpose when it was created :)

At one of the clients they use **intercept** along with https://www.shellcheck.net/

Give it a try on the PLAYGROUND using gitpod :
https://github.com/xfhg/intercept#playground
